---
version: '3'

services:
  web:
    tty: true
    stdin_open: true
    build:
      context: .
    command: bin/rails s
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development

volumes:
  bundle:
